import Head from 'next/head'
import Layout from '../components/layout'
import Image from 'next/image';
import logo from '../content/images/equipement.jpg'

export default function About() {
  return (
    <Layout>
      <Head>
        <title>About Uski</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='relative overflow-hidden block border-b-2 border-black w-full bg-accueilphone bg-no-repeat bg-cover  md:bg-accueil'>
        <div className='justify-center flex ' id='accueil'>
          <div className=' mx-12 my-0 min-w-0 max-w-6xl w-full block '>
            <div className=' mb-12 block m-auto md:text-center' id='titre'>
              <h1 className="text-4xl mt-24  md:text-7xl font-snowky text-black font-bold m-4 block tracking-wide rounded">
                U ski together !
              </h1>
              <p className=' text-3xl font-chritsmas font-bold text-black rounded'>
                Nous sommes une entreprise de vente de skis qui favorise la puissance, la solidité,  le calme et la performance. <br></br>

              </p>
            </div>
            <div className='flex-row flex w-full'>
              <div className=' w-96 z-10 flex-col h-full pb-24 flex dark:text-black'>

                <div className=' w-4/5 mb-12 block'>


                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <hr className='h-1 bg-black'></hr>
      <div className='relative py-5 px-5 ml-auto mr-auto w-full md:grid-cols-2 lg:gap-x-16 grid items-center grid-cols-1'>
        <div className='flex items-center'>
          <div>
            <h2 className='text-3xl text-center md:text-5xl font-chritsmas mb-8'>
              Nous mettons un point d'honneur sur la qualité et la durabilité de nos skis et priorisons le bonheur de nos clients.
            </h2>
          </div>
        </div>
        <div className='invisible md:visible md:max-w-lg mx-auto overflow-hidden rounded-lg shadow-xl'>
            <Image
              src={logo}
              alt="Picture of the player"
              height={438}
              width={600}
            />
          </div>
      </div>
      <hr className='h-1 bg-black'></hr>
      <hr className='h-1 bg-black'></hr>

      {/*
      <div class="flex bg-white shadow-lg rounded-lg mx-4 md:mx-auto my-56 max-w-md md:max-w-2xl content-center ">
        <div class="flex items-start px-4 py-6">
          <div class="">
            <Gravatar class="w-12 h-12 rounded-full object-cover mr-4 shadow" email="saccoman.lu@gmail.com" />
            <div class="">
              <div class="flex items-center justify-between">
                <h2 class="text-lg font-semibold text-gray-900 -mt-1">Lucas Saccoman </h2>
              </div>
            </div>
            <br />
            <Gravatar class="w-12 h-12 rounded-full object-cover mr-4 shadow" email="alexandre.correia@edu.ece.fr" />
            <div class="">
              <div class="flex items-center justify-between">
                <h2 class="text-lg font-semibold text-gray-900 -mt-1">Alexandre Correia </h2>
              </div>
            </div>
          </div>
          <p class="text-gray-700">_</p>
          <p class="mt-3 text-gray-700 text-sm">
            Welcome to our portfolio! We are two engineering students studying computer science and passionate about technology and programming. Our portfolio was created as part of a school project to showcase the skills and knowledge we have gained through our studies.
            <br /><br />
            In this portfolio, you will find examples of the projects we have worked on, as well as information about our background and interests. We are committed to continuously learning and staying up-to-date on the latest developments in the field, and we hope that our portfolio reflects this dedication.
            <br /><br />
            Thank you for taking the time to visit our portfolio. We hope you find it informative and interesting, and we welcome any feedback or suggestions you may have.
          </p>
          <div class="mt-4 flex items-center">
          </div>
        </div>
      </div> */}
    </Layout>
  )
}